### ISSUE TITLE
not working...

### ISSUE THREAD

**Issue by sonic-iso** [ajgon/bgtoolset#1]
hey man, i hosted these files on www.funsploits.com since im sure ps3xploit is infact now down forever. it doesnt seem to be triggering the exploit. i even went into the htmls and changed all the domains from ps3xploit to mine. i already prepaid for a couple years so to get this up and running for veryone would be grand.

**Comment by ajgon** [comment]
Hey,

I can't help you with that, sorry. As I mentioned in the docs, these dump is for private use only, and completely at your own risk. I also don't provide any help or support to these files - because I'm not the author, so I don't even know how they work.

You're on your own, sorry, but good luck!

**Comment by sonic-iso** [comment]
its all good i ended  up figuring it out. it was like 4am and i was half asleep working on it. i have it hosted on www.funsploit.com since the dev decided to close the site. i need to ump www.pspx.ru/forum/bgtoolset. that link has support for 4.89!! i tried httrack and wget however i think theyhave some security set in place. i tried different variations of tweaks with spider and no luck, if you can dump it it would be of huge help!
