### ISSUE TITLE
CECHE01 on 4.89 OFW Patch Success

### ISSUE THREAD

**Issue by stanleyws** [ajgon/bgtoolset#14]
Successfully patched a CECHE01 (NAND) console on 4.89 today. The patching process is pretty fast (about 5 seconds) and finished without any error. However, the console won't power up anymore after turning it off (green light for about 10 seconds, hdd light flashes then console turns off, no beep). Booting into recovery mode and installing cfw from usb seems to fix the problem.

Thank you so much for keeping a backup on github.

**Comment by ajgon** [comment]
Added to the list, thanks for the info and the kind words :)

**Comment by stanleyws** [comment]
Did another CECHA01 (NAND) console today, patch applied without any error, but console won't power on anymore. Had to reinstall cfw in recovery menu. Also tried the flash dumping tool which works as expected, the dumped hex file passes all checks in PyPS3checker.

```
******* Checks completed *******

Total number of checks = 113
Number of dangers = 0
Number of warnings = 0

All checks done in 1.43 seconds.
````

Btw I got several clock errors when running it on my ps3 today, although the time on my ps3 is correct:
`This project requires the ps3 clock to be adequately set`

Also tried to open it on my computer's web browser, same error. I think there might be some bug in get_day() function (different time zone maybe? I didn't get the error yesterday when I used it at a different time). 

Anyway I just patched out the time check function on line 565 as I'm running everything locally with XAMPP over plain http, no SSL involved.

`if( false /*get_day()!== cdate.getUTCDay().toString() || get_year() !== cdate.getUTCFullYear().toString()*/){`

**Comment by ajgon** [comment]
I think the problem lies here: https://github.com/ajgon/bgtoolset/blob/903b0f3b1dc3248a44185d8368fc9a6cab0cb33a/index.php#L77
and here (the line you commented out): https://github.com/ajgon/bgtoolset/blob/903b0f3b1dc3248a44185d8368fc9a6cab0cb33a/index.php#L565

Looks like the first one tries to preserve timezone if it's set on the system (and only default to UTC if not), while the other expects UTC all the time. I fixed it [here](https://github.com/ajgon/bgtoolset/commit/e101583da9e34ea044d2c862079480d724b65c28) - hopefully this will help.

Thanks again for the feedback!
